on:
  release:
    types:
      - 'created'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - uses: ko-build/setup-ko@v0.8
      - uses: azure/setup-helm@v4.3.0
      - run: |
          TAG=${{ github.ref_name }}
          ko build --bare -t $TAG
          yq -i '.image.tag = "'$TAG'"' deploy/transip-webhook/values.yaml
          helm package ./deploy/transip-webhook --version $TAG --app-version $TAG
          helm push ./transip-webhook-$TAG.tgz oci://ghcr.io/lion7/cert-manager-webhook-transip
          helm template -n cert-manager transip-webhook ./transip-webhook-$TAG.tgz > recommended.yaml
          gh release upload $TAG recommended.yaml
